import {NoticeModal,confirmDialog,notifyDialog} from './Notifications';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Heart,Lightbulb,Play,RotateCcw,Undo2,CheckCircle2,Flag,Code2,Layers,BarChart3,Shield,Route} from 'lucide-react';
import {api} from '../lib';
import RobotGrid from './RobotGrid';
import GuideTask from './GuideTask';
import WorldAdventure from './WorldAdventure';
const labels={E:'→ ขวา',S:'↓ ลง',W:'← ซ้าย',N:'↑ ขึ้น',E2:'วนซ้ำ 2 × [→]',E3:'วนซ้ำ 3 × [→]',ES2:'วนซ้ำ 2 × [→ ↓]'};
const taskInstructions={picture:'เลือกรูปลงแต่ละช่องให้ตรงคำสั่ง ช่องอื่นให้ว่าง',numbergrid:'เติมเลข 1–4 ตรวจทั้งแถว คอลัมน์ และกรอบ 2×2',worksheet:'อ่านตาราง แล้วกรอกผลคำนวณให้ครบทุกช่อง',sequence:'แตะบัตรตามลำดับที่ต้องการ แล้วยืนยันคำตอบ',sort:'อ่านบัตรแต่ละใบแล้วเลือกกลุ่มให้ครบ',chart:'นับข้อมูลแล้วปรับความสูงแท่งให้ตรงกับจำนวน',scenario:'อ่านสถานการณ์และเลือกการกระทำที่เหมาะสม',program:'ต่อบล็อกคำสั่งแล้วกดรันเพื่อตรวจเส้นทาง',choice:'อ่านโจทย์และเลือกคำตอบที่มีเหตุผล'};
const taskLabels={picture:'ศิลปะบนตาราง',numbergrid:'ปริศนาตารางตัวเลข',worksheet:'โต๊ะคำนวณข้อมูล',sequence:'สะพานเรียงลำดับ',sort:'คลังคัดแยก',chart:'นักสร้างแผนภูมิ',scenario:'ภารกิจตัดสินใจ',program:'ห้องทดลองหุ่นยนต์'};
const icons={sequence:Route,program:Code2,sort:Layers,chart:BarChart3,scenario:Shield};

export default function MissionGame({level,initialAttempt,onExit,onComplete,onReflect}){
 const [attempt,setAttempt]=useState(initialAttempt),[q,setQ]=useState(null),[draft,setDraft]=useState(null),[feedback,setFeedback]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[hint,setHint]=useState(false),[animating,setAnimating]=useState(false);
 const requestBusy=useRef(false),mounted=useRef(true);const Icon=icons[q?.kind]||icons[level.mode]||Flag;
 const load=async()=>{setError('');setBusy(true);try{const d=await api(`/attempts/${initialAttempt.id}/question`);if(!mounted.current)return;const item=d.question;setQ(item);setDraft(item.kind==='picture'?item.cards.map(()=>0):item.kind==='numbergrid'?item.givens.map(n=>n||''):item.kind==='worksheet'?item.fields.map(()=>''):item.kind==='sequence'?[]:item.kind==='program'?[...item.initial]:item.kind==='sort'?item.cards.map(()=>-1):item.kind==='chart'?item.categories.map(()=>0):null);setFeedback(null);setHint(false);}catch(e){if(mounted.current)setError(e.message);}finally{if(mounted.current)setBusy(false);}};
 useEffect(()=>{mounted.current=true;load();return()=>{mounted.current=false;};},[initialAttempt.id]);

 async function submit(){if(requestBusy.current||feedback)return;requestBusy.current=true;setBusy(true);setError('');try{const data=await api(`/attempts/${attempt.id}/answer`,{method:'POST',body:{question_id:q.id,choice:draft}});if(mounted.current){setAttempt(data.attempt);setFeedback(data);}}catch(e){setError(e.message);}finally{requestBusy.current=false;setBusy(false);}}
 async function next(){if(requestBusy.current)return;if(attempt.status==='failed'){setResult({won:false});return;}if(attempt.answered<3){await load();return;}if(attempt.correct<2){setResult({won:false});return;}requestBusy.current=true;setBusy(true);setError('');try{const d=await api(`/attempts/${attempt.id}/finish`,{method:'POST'});setAttempt(d.attempt);setResult({won:true,profile:d.profile});onComplete(d.profile);}catch(e){setError(e.message);}finally{requestBusy.current=false;setBusy(false);}}
 const ready=q&&(['worksheet','numbergrid'].includes(q.kind)?draft?.every(n=>Number.isInteger(n)):q.kind==='picture'?true:q.kind==='sequence'?draft?.length===q.cards.length:q.kind==='program'?draft?.length>0:q.kind==='sort'?draft?.every(i=>i>=0):q.kind==='chart'?true:draft!==null);
 const disabled=busy||!!feedback;
 return <section className={`mission-screen unit-${level.unit}`}><div className="game-heading"><button className="icon-btn" onClick={onExit} aria-label="ออกจากด่าน"><ArrowLeft/></button><div><small>โลก {level.unit} · ด่าน {level.number} · {level.difficulty}</small><h2>{level.title}</h2></div><span className="mission-mode"><Icon size={18}/>{taskLabels[q?.kind]||level.mode_label}</span></div>
 <div className="mission-top"><span className="hearts" aria-label={`หัวใจ ${attempt.hearts} ดวง`}>{[0,1,2].map(i=><Heart key={i} size={22} color={i<attempt.hearts?'#df7460':'#a6b19c'} fill={i<attempt.hearts?'#df7460':'transparent'}/>)}</span><span>🍄 {attempt.correct} / 3</span><div className="mission-steps">{[0,1,2].map(i=><span key={i} className={i<attempt.answered?(attempt.answers[i]?.correct?'passed':'missed'):i===attempt.answered?'current':''}>{i<attempt.answered?(attempt.answers[i]?.correct?'✓':'×'):i+1}</span>)}</div><span className="untimed">คิดได้เต็มที่ · ไม่จับเวลา</span></div>
 {result?<div className="mission-result"><div className="result-icon">{result.won?'🏆':'🌱'}</div><span className="eyebrow">{result.won?'MISSION COMPLETE':'LEARN & TRY AGAIN'}</span><h1>{result.won?'ผ่านด่านสำเร็จ!':'เริ่มใหม่ได้ เก่งขึ้นแน่นอน'}</h1><p>{result.won?`ได้รับ ${level.reward}`:'กลับไปดูตัวอย่าง แล้วลองใช้สิ่งที่เรียนรู้แก้ภารกิจอีกครั้ง'}</p><div className="result-stats"><span>🍄 {attempt.correct} ดอก</span><span>สำเร็จ {attempt.correct} / 3 ภารกิจ</span></div><p>{result.won?'คะแนนดีที่สุดและรางวัลบันทึกแล้ว':'รอบนี้ยังไม่เพิ่มคะแนนสะสม ต้องสำเร็จอย่างน้อย 2 ภารกิจ'}</p><button className="primary" onClick={onExit}>{result.won?'กลับแผนที่ผจญภัย':'กลับไปทบทวน / เริ่มใหม่'}<ArrowRight size={18}/></button>{result.won&&onReflect&&<button className="secondary" onClick={onReflect}>เขียนสมุดสะท้อนคิด</button>}</div>:q?<WorldAdventure unit={level.unit} attempt={attempt} question={q} feedback={feedback}><div className="mission-layout"><div className="mission-board"><div className="mission-question"><span className="eyebrow">ภารกิจ {feedback?attempt.answered:attempt.answered+1} / 3</span><h2>{q.prompt}</h2><p>{taskInstructions[q.kind]||level.instructions}</p></div>
 {['picture','numbergrid','worksheet'].includes(q.kind)&&<GuideTask q={q} draft={draft} setDraft={setDraft} disabled={disabled}/>}
 {q.kind==='sequence'&&<><div className="sequence-slots" aria-label="ลำดับคำตอบ">{q.cards.map((_,i)=><div className={`sequence-slot ${draft[i]!==undefined?'filled':''}`} key={i}><span>{i+1}</span>{draft[i]!==undefined?q.cards[draft[i]]:'เลือกบัตรด้านล่าง'}</div>)}</div><div className="card-bank">{q.cards.map((card,i)=><button key={i} className="task-card" disabled={disabled||draft.includes(i)} onClick={()=>setDraft([...draft,i])}>{card}<ArrowRight size={15}/></button>)}</div><div className="draft-tools"><button className="secondary" disabled={disabled||!draft.length} onClick={()=>setDraft(draft.slice(0,-1))}><Undo2 size={16}/> ย้อนหนึ่งบัตร</button><button className="icon-btn" disabled={disabled} onClick={()=>setDraft([])} aria-label="ล้างลำดับ"><RotateCcw size={18}/></button></div></>}
 {q.kind==='sort'&&<div className="sorting-cards">{q.cards.map((card,i)=><div key={i} className="sorting-card"><span className="card-index">{i+1}</span><strong>{card}</strong><label><span className="sr-only">กลุ่มของ {card}</span><select disabled={disabled} aria-label={`กลุ่มของ ${card}`} value={draft[i]} onChange={e=>setDraft(draft.map((v,j)=>j===i?Number(e.target.value):v))}><option value={-1}>เลือกกลุ่ม…</option>{q.categories.map((cat,j)=><option key={j} value={j}>{cat}</option>)}</select></label></div>)}</div>}
 {q.kind==='program'&&<div className="program-workbench"><div><RobotGrid key={q.id} size={q.size} start={q.start} goal={q.goal} walls={q.walls} result={feedback} onPlaying={setAnimating}/><p className="grid-caption">🤖 เริ่ม · 🪨 ห้ามเดินทับ · 🚩 เป้าหมาย<br/>พิกัด: คอลัมน์, แถว (นับจากซ้ายบน)</p></div><div className="code-editor"><strong>ชุดคำสั่งของฉัน <small>{draft.length}/{q.max_commands} บล็อก</small></strong><div className="code-slots">{draft.length?draft.map((token,i)=><button key={i} disabled={disabled} className="code-block" onClick={()=>setDraft(draft.filter((_,j)=>j!==i))} aria-label={`ลบบล็อก ${i+1} ${labels[token]}`}><span>{i+1}</span>{labels[token]}<span>×</span></button>):<p>แตะบล็อกด้านล่าง<br/>เพื่อต่อคำสั่ง</p>}</div><div className="block-palette">{q.palette.map(token=><button className="secondary" key={token} disabled={disabled||draft.length>=q.max_commands} onClick={()=>setDraft([...draft,token])} aria-label={`เพิ่ม ${labels[token]}`}>{labels[token]}</button>)}</div><button className="text-button" disabled={disabled} onClick={()=>setDraft([])}><RotateCcw size={14}/> ล้างคำสั่ง</button></div></div>}
 {q.kind==='chart'&&<><div className="raw-data"><strong>ข้อมูลดิบ · {q.records.length} คำตอบ</strong><div>{q.records.map((r,i)=><span key={i}>{r}</span>)}</div></div><div className="chart-axis-label">จำนวนคำตอบ (คน)</div><div className="chart-workbench">{q.categories.map((cat,i)=><div className="chart-column" key={cat}><strong>{draft[i]}</strong><div className="bar-space"><div className="editable-bar" style={{height:`${draft[i]/q.records.length*100}%`}}/></div><span>{cat}</span><div className="bar-controls"><button aria-label={`ลด ${cat}`} disabled={disabled||draft[i]===0} onClick={()=>setDraft(draft.map((v,j)=>i===j?v-1:v))}>−</button><button aria-label={`เพิ่ม ${cat}`} disabled={disabled||draft[i]>=q.records.length} onClick={()=>setDraft(draft.map((v,j)=>i===j?v+1:v))}>+</button></div></div>)}</div><p className="chart-total">รวมในแผนภูมิ {draft.reduce((a,b)=>a+b,0)} / {q.records.length} คำตอบ</p></>}
 {(q.kind==='scenario'||q.kind==='choice')&&<><div className="scenario-scene"><span>{level.unit===4?'🛡️':level.unit===3?'🔎':'🚪'}</span><div><small>สถานการณ์จำลอง</small><p>{q.context||level.example}</p></div></div><div className="scenario-options">{q.options.map((o,i)=><button className={`answer ${draft===i?'selected':''}`} key={i} disabled={disabled} onClick={()=>setDraft(i)}><span>{'กขคง'[i]}</span>{o}</button>)}</div></>}
 {feedback?<div className={`mission-feedback ${feedback.correct?'success':'retry'}`} role="status"><h3>{feedback.correct?'สำเร็จ! รับเห็ด 1 ดอก 🍄':'ยังไม่สำเร็จ ลองดูเหตุผลกัน'}</h3><p>{feedback.explanation}</p>{!feedback.correct&&<details><summary>ดูตัวอย่างคำตอบที่ถูกต้อง</summary><p>{feedback.solution}</p></details>}<small>{feedback.correct?'+100 คะแนนในการเล่นรอบนี้':'เสียหัวใจ 1 ดวง · ความผิดพลาดช่วยให้เรียนรู้'}</small><button className="primary" disabled={busy||animating} onClick={next}>{animating?'กำลังแสดงเส้นทาง…':busy?'กำลังบันทึก…':attempt.status==='failed'||attempt.answered===3?'ดูผลการผจญภัย':'ภารกิจถัดไป'}<ArrowRight size={17}/></button></div>:<button className="primary full mission-submit" disabled={!ready||busy} onClick={submit}>{q.kind==='program'?<Play size={18}/>:<CheckCircle2 size={18}/>} {busy?'กำลังตรวจ…':q.kind==='program'?'รันคำสั่งและตรวจผล':'ตรวจภารกิจ'}</button>}
 {error&&<NoticeModal message={error} onClose={()=>setError('')}/>}</div><aside className="mission-guide"><div><Lightbulb size={23}/><h3>หยุดคิดสักนิด</h3><p>ตรวจคำตอบก่อนส่ง<br/>ทุกภารกิจมีเวลาให้คิดเต็มที่</p><button className="secondary" onClick={()=>setHint(!hint)}>{hint?'ซ่อนคำใบ้':'ขอคำใบ้'}</button>{hint&&<p className="hint-text">{q.hint}</p>}</div><div><h3>ทักษะที่กำลังฝึก</h3><p>{level.subtitle}</p><small>{level.rationale}</small></div><div className="guide-rules"><strong>กติกาของด่าน</strong><p>3 ภารกิจ · สำเร็จอย่างน้อย 2 ภารกิจเพื่อผ่าน<br/>พลาดเสียหัวใจ 1 ดวง<br/>ครบ 3 ครั้ง เริ่มใหม่ได้เสมอ</p><small>ใช้คำใบ้ได้โดยไม่หักคะแนน</small></div></aside></div></WorldAdventure>:<div className="empty"><p>กำลังเตรียมภารกิจ…</p><button className="primary" onClick={load}>ลองโหลดอีกครั้ง</button>{error&&<NoticeModal message={error} onClose={()=>setError('')}/>}</div>}
 </section>;
}
