import {NoticeModal,confirmDialog,notifyDialog} from './Notifications';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,FilePenLine,Lightbulb,Save,Send,Play,RotateCcw,MessageSquare,Lock} from 'lucide-react';
import {api} from '../lib';
import RobotGrid from './RobotGrid';
import {randomRobotMap} from '../lib/randomRobotMap';
const states={draft:'ร่างส่วนตัว',submitted:'ส่งแล้ว รอครูอ่าน',revision_requested:'ครูแนะนำให้ปรับปรุง',reviewed:'ครูให้ข้อเสนอแนะแล้ว'};
const rubricNames={reasoning:'การอธิบายเหตุผล',evidence:'หลักฐานและผลทดลอง',transfer:'การนำไปใช้'};
const rubricLevels={developing:'ยังต้องช่วยคิด',progressing:'กำลังพัฒนา',clear:'อธิบายได้ชัดเจน'};
const commandLabels={E:'→ ขวา',S:'↓ ลง',W:'← ซ้าย',N:'↑ ขึ้น',E2:'วนซ้ำ 2 × [→]',E3:'วนซ้ำ 3 × [→]',ES2:'วนซ้ำ 2 × [→ ↓]'};
const defaultArtifact=(unit)=>unit<=2?randomRobotMap():unit===3?{question:'',source:'',records:[]}:{story:'',choices:['','',''],outcomes:['','',''],safe:0};
const date=s=>new Date(s).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'});
function History({items,fields,scope,kind}){return <div className="work-history"><h3>ฉบับที่ส่งและข้อเสนอแนะ</h3>{items.length?items.map((s,i)=><details key={s.id} open={i===0}><summary>ฉบับที่ {s.revision} · {date(s.submitted_at)} · {s.outcome?states[s.outcome]:'รอข้อเสนอแนะ'}</summary>{s.feedback&&<div className="teacher-feedback"><strong>💬 ข้อเสนอแนะจากครู</strong><p>{s.feedback}</p>{Object.entries(s.rubric||{}).map(([k,v])=><span key={k}>{rubricNames[k]}: {rubricLevels[v]}</span>)}</div>}<details><summary>ดูผลงานฉบับนี้</summary><ReadContent content={s.content} fields={fields} kind={kind} scope={scope}/></details></details>):<p className="muted">ยังไม่มีฉบับที่ส่ง ร่างนี้เห็นได้เฉพาะตัวนักเรียน</p>}</div>;}

export default function Portfolio({view,levels,teacher=false,initialScope,onDirty=()=>{}}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[selected,setSelected]=useState(initialScope||null),[dirty,setDirty]=useState(false);
 const kind=view==='journal'?'journal':'project';
 const load=async()=>{try{setData(await api(teacher?'/teacher/portfolio':'/portfolio'));setError('');}catch(e){setError(e.message);}};
 useEffect(()=>{load();return()=>onDirty(false);},[]);
 const changed=v=>{setDirty(v);onDirty(v);};
 const navigate=async id=>{if(dirty&&!await confirmDialog('มีข้อความที่ยังไม่ได้บันทึก ต้องการออกจากฉบับนี้หรือไม่?'))return;changed(false);setSelected(id);};
 if(!data)return <div className="empty"><p>กำลังเปิดสมุดและผลงาน…</p><button className="secondary" onClick={load}>ลองใหม่</button>{error&&<NoticeModal message={error} onClose={()=>setError('')}/>}</div>;
 if(teacher)return <TeacherPortfolio data={data} levels={levels} reload={load} onDirty={onDirty}/>;
 const specs=kind==='project'?data.projects:levels.map(l=>({id:l.id,title:`ด่าน ${l.number} · ${l.title}`,world:`โลก ${l.unit}`,unlocked:data.journal_unlocked.includes(l.id)}));
 const selectedSpec=specs.find(s=>s.id===selected);const spec=kind==='project'&&selectedSpec?.id<=2?{...selectedSpec,brief:selectedSpec.id===1?'วางแผนเส้นทางในเขาวงกตที่ระบบเตรียมให้ แล้วอธิบายว่ารู้ได้อย่างไรว่าเส้นทางใช้ได้':'สร้างชุดคำสั่งให้หุ่นยนต์ถึงธงในแผนที่ที่ระบบเตรียมให้ แล้วเปรียบเทียบผลกับสิ่งที่คาดไว้',steps:['สำรวจจุดเริ่ม ธง และหินบนตาราง',...selectedSpec.steps.slice(1)]}:selectedSpec;const work=data.works.find(w=>w.kind===kind&&w.scope_id===selected);
 const fields=kind==='project'?data.project_fields:data.journal_fields;
 const update=w=>{setData({...data,works:[...data.works.filter(x=>!(x.kind===w.kind&&x.scope_id===w.scope_id)),w]});changed(false);};
 return <section className="portfolio"><div className="page-heading"><div><span className="eyebrow">{kind==='project'?'MAKE • TEST • EXPLAIN':'MY LEARNING JOURNAL'}</span><h1>{kind==='project'?'ภารกิจสร้างผลงาน':'สมุดสะท้อนคิด'}</h1><p>{kind==='project'?'เปลี่ยนสิ่งที่เรียนให้เป็นผลงานของตัวเอง':'เขียนด้วยคำของเรา ว่าคิด ทดลอง และเข้าใจอะไรเพิ่มขึ้น'}</p></div></div><div className="portfolio-intro"><Lightbulb size={22}/><p>ร่างเห็นได้เฉพาะเรา ครูจะเห็นเมื่อกดส่ง · บันทึกกลับมาแก้ได้ · ไม่เพิ่มหรือลดคะแนนอันดับเกม</p></div>
 {error&&<NoticeModal message={error} onClose={()=>setError('')}/>}
 {spec?<><button className="text-button work-back" onClick={()=>navigate(null)}><ArrowLeft size={17}/> กลับรายการ{kind==='project'?'ผลงาน':'บันทึก'}</button><WorkEditor key={`${kind}-${selected}`} spec={spec} kind={kind} work={work} fields={fields} onChange={changed} onUpdate={update} onReload={async()=>{if(dirty&&!await confirmDialog('โหลดฉบับล่าสุดจะทิ้งข้อความที่ยังไม่บันทึก ต้องการดำเนินการหรือไม่?'))return;changed(false);await load();}}/>
 </>:<div className={`portfolio-list ${kind==='journal'?'journal-list':''}`}>{specs.map(s=>{const w=data.works.find(w=>w.kind===kind&&w.scope_id===s.id);return <button className="portfolio-card" key={s.id} onClick={()=>navigate(s.id)}><span className="portfolio-card-icon">{kind==='journal'?'📓':['🧭','🤖','📊','🛡️'][s.id-1]}</span><span><small>{s.world}</small><strong>{s.title}</strong>{s.brief&&<p>{s.brief}</p>}<span className={`work-state ${w?.state||'draft'}`}>{w?states[w.state]:'เริ่มร่างได้เลย'}</span><small className="work-availability">{s.unlocked?'พร้อมส่งให้ครู':kind==='project'?'ร่างได้ · ผ่าน 6 ด่านพื้นฐานเพื่อส่ง':'ร่างได้ · ผ่านด่านนี้เพื่อส่ง'}</small></span><ArrowRight size={18}/></button>;})}</div>}
 </section>;
}

function WorkEditor({spec,kind,work,fields,onChange,onUpdate,onReload}){
 const [form,setForm]=useState(()=>({...Object.fromEntries(fields.map(([k])=>[k,''])),...(kind==='project'?{artifact:defaultArtifact(spec.id)}:{}),...(work?.content||{})})),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[dirty,setDirty]=useState(false),[test,setTest]=useState(null),[playing,setPlaying]=useState(false);
 const locked=!!work&&work.state!=='draft';
 useEffect(()=>{if(work){setForm(work.content);setDirty(false);onChange(false);}},[work?.version]);
 useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const change=(key,value)=>{setForm(f=>({...f,[key]:value}));setDirty(true);onChange(true);setNote('');if(key==='artifact')setTest(null);};
 async function action(name){if(busy)return;setBusy(true);setError('');try{
   let current=work;
   if(name==='save'||name==='submit'){const saved=await api(`/portfolio/${kind}/${spec.id}`,{method:'PUT',body:{version:work?.version||0,content:form}});current=saved.work;onUpdate(current);setDirty(false);}
   if(name==='submit'||name==='revise'){const r=await api(`/portfolio/${kind}/${spec.id}/${name}`,{method:'POST',body:{version:current.version}});onUpdate(r.work);}
   const message=name==='save'?'บันทึกร่างแล้ว':name==='submit'?'ส่งให้ครูแล้ว':'เปิดฉบับแก้ไขแล้ว';setNote(message);notifyDialog(message);
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 async function run(){setBusy(true);setError('');try{setTest(await api(`/portfolio/projects/${spec.id}/simulate`,{method:'POST',body:{artifact:form.artifact}}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="work-layout"><div className="work-editor"><div className="work-title"><span className="eyebrow">{spec.world}</span><h2>{spec.title}</h2><span className={`work-state ${work?.state||'draft'}`}>{states[work?.state||'draft']}</span>{work&&<small>บันทึกล่าสุด {date(work.updated_at)}</small>}</div>
 {locked&&<div className="notice">ฉบับนี้ส่งแล้ว หากต้องการปรับปรุงให้กด “สร้างฉบับแก้ไข” ฉบับที่ส่งและข้อเสนอแนะเดิมจะยังอยู่</div>}
 {kind==='project'&&<><fieldset disabled={locked||busy||playing} className="work-fieldset"><label>ชื่อผลงาน<input value={form.title} maxLength={1800} onChange={e=>change('title',e.target.value)} placeholder="ตั้งชื่อผลงานในแบบของเรา"/></label></fieldset><ArtifactEditor unit={spec.id} value={form.artifact} onChange={a=>change('artifact',a)} test={test} onRun={run} onPlaying={setPlaying} disabled={locked||busy} playing={playing} onRestart={()=>{setTest(null);setPlaying(false);setError('');setNote('หุ่นยนต์กลับจุดเริ่มต้นแล้ว พร้อมทดลองคำสั่งเดิม');}}/></>}
 <fieldset disabled={locked||busy||playing} className="work-fieldset">
 <div className="reflection-steps">{fields.filter(([key])=>key!=='title').map(([key,label],i)=><label key={key}><span><b>{i+1}</b> {label}</span><textarea rows={3} maxLength={1800} value={form[key]} onChange={e=>change(key,e.target.value)} placeholder="อธิบายด้วยคำของเรา พร้อมยกตัวอย่างที่พบ"/><small>{form[key].length}/1,800 ตัวอักษร</small></label>)}</div>
 </fieldset>
 <div className="work-actions">{locked?<button className="primary" disabled={busy||playing} onClick={()=>action('revise')}><FilePenLine size={17}/> สร้างฉบับแก้ไข</button>:<><button className="secondary" disabled={busy||playing} onClick={()=>action('save')}><Save size={17}/> บันทึกร่าง</button><button className="primary" disabled={busy||playing||!spec.unlocked} onClick={()=>action('submit')}><Send size={17}/> {busy?'กำลังบันทึก…':'บันทึกและส่งให้ครู'}</button></>}</div>
 {!spec.unlocked&&<p className="notice">{kind==='project'?'ผ่าน 6 ด่านพื้นฐานของโลกนี้ก่อนส่งผลงาน':'ผ่านด่านนี้ก่อนส่งสมุดสะท้อนคิด'} ระหว่างนี้บันทึกร่างได้ทุกเมื่อ</p>}
 <p className="save-indicator" role="status">{dirty?'มีการแก้ไขที่ยังไม่บันทึก':note||(work?'บันทึกแล้ว':'ยังไม่ได้บันทึก')}</p>
 {error&&<NoticeModal message={error} onClose={()=>setError('')}><button type="button" className="secondary" onClick={()=>{setError('');onReload();}}>โหลดฉบับล่าสุด</button></NoticeModal>}
 <History items={work?.submissions||[]} fields={fields} scope={spec.id} kind={kind}/>
 </div><aside className="work-guide"><h3>ก่อนเริ่มลงมือ</h3><p>{spec.brief||'ไม่ต้องเขียนให้เหมือนตัวอย่าง เล่าจุดที่เปลี่ยนความคิดหรือสิ่งที่ยังสงสัยได้'}</p>{spec.steps&&<ol>{spec.steps.map(s=><li key={s}>{s}</li>)}</ol>}<h3>ครูจะอ่านอะไรบ้าง</h3><ul>{(spec.criteria||['สิ่งที่เข้าใจด้วยคำของนักเรียน','ตัวอย่างหรือหลักฐานที่อธิบายความเข้าใจ','สิ่งที่อยากลองต่อและการนำไปใช้']).map(c=><li key={c}>{c}</li>)}</ul><div className="notice">เขียนเรื่องสมมติหรือข้อมูลที่ไม่ระบุชื่อคน ไม่ใส่รหัสผ่าน ที่อยู่ หรือเบอร์โทรของใคร</div><p>ผลงานไม่มีการตัดสินถูกผิดอัตโนมัติ ครูจะอ่านเหตุผลและให้ข้อเสนอแนะ</p></aside></div>;
}

function ArtifactEditor({unit,value,onChange,test,onRun,onPlaying,onRestart,disabled,playing}){
 const a=value;const change=(k,v)=>onChange({...a,[k]:v});
 if(unit<=2){
 return <div className="artifact-editor"><fieldset disabled={disabled||playing} className="work-fieldset"><h3>แผนที่และคำสั่งของเรา</h3><RobotGrid className="authoring-grid" start={a.start} goal={a.goal} walls={a.walls} result={test} onPlaying={onPlaying}/><p className="grid-caption">วางแผนคำสั่งให้ถึงธงและหลบหิน · เส้นทางทดลองแสดงด้วยสีเขียว</p><h3>คำสั่งของเรา ({a.commands.length}/30)</h3><div className="authored-commands">{a.commands.map((t,i)=><button type="button" key={i} className="code-block" aria-label={`ลบคำสั่ง ${i+1}`} onClick={()=>change('commands',a.commands.filter((_,j)=>i!==j))}>{i+1}. {commandLabels[t]} ×</button>)}</div><div className="block-palette">{Object.entries(commandLabels).filter(([t])=>unit===2||t.length===1).map(([t,label])=><button type="button" className="secondary" key={t} disabled={a.commands.length>=30} onClick={()=>change('commands',[...a.commands,t])}>เพิ่ม {label}</button>)}</div></fieldset><div className="robot-restart-tools"><button type="button" className="secondary" onClick={onRun} disabled={disabled||playing||!a.commands.length}><Play size={17}/> ทดลองผลงาน</button><button type="button" className="secondary" onClick={onRestart} disabled={disabled}><RotateCcw size={17}/> เริ่มใหม่</button></div>{test&&<div className={`mission-feedback ${test.success?'success':'retry'}`} role="status"><strong>{test.message}</strong><p>เดินได้ {test.trace.length-1} ก้าว ลองเทียบกับสิ่งที่คาดไว้ แล้วบันทึกหลักฐานด้านล่าง</p></div>}</div>;
 }
 if(unit===3)return <fieldset disabled={disabled} className="artifact-editor work-fieldset"><label>คำถามที่ต้องการสำรวจ<input value={a.question} maxLength={600} onChange={e=>change('question',e.target.value)} placeholder="เช่น กลุ่มที่สำรวจชอบผลไม้ชนิดใด"/></label><label>แหล่งข้อมูล / กลุ่มที่สำรวจ (ไม่ระบุชื่อคน)<input value={a.source} maxLength={600} onChange={e=>change('source',e.target.value)} placeholder="เช่น เพื่อน 5 คนในห้อง โดยไม่บันทึกชื่อ"/></label><label>คำตอบที่เก็บได้ (หนึ่งคำตอบต่อบรรทัด)<textarea rows={7} maxLength={3050} value={a.records.join('\n')} onChange={e=>change('records',e.target.value.split('\n'))} placeholder={'แมว\nสุนัข\nแมว'}/></label><small>ไม่เกิน 50 รายการ และ 8 ประเภท เขียนชื่อประเภทให้ตรงกัน</small><DataChart records={a.records}/></fieldset>;
 return <fieldset disabled={disabled} className="artifact-editor work-fieldset"><label>สถานการณ์สมมติ<textarea rows={4} maxLength={1800} value={a.story} onChange={e=>change('story',e.target.value)} placeholder="แต่งเหตุการณ์ที่ต้องคิดเรื่องความปลอดภัยหรือสิทธิของผู้อื่น"/></label>{a.choices.map((v,i)=><div className="story-choice" key={i}><label>ทางเลือกที่ {i+1}<input maxLength={600} value={v} onChange={e=>change('choices',a.choices.map((c,j)=>i===j?e.target.value:c))}/></label><label>ผลที่อาจตามมาจากทางเลือกที่ {i+1}<textarea maxLength={600} rows={2} value={a.outcomes[i]} onChange={e=>change('outcomes',a.outcomes.map((c,j)=>i===j?e.target.value:c))}/></label></div>)}<label>ทางเลือกที่ฉันเห็นว่าปลอดภัยที่สุด<select aria-label="ทางเลือกที่ฉันเห็นว่าปลอดภัยที่สุด" value={a.safe} onChange={e=>change('safe',Number(e.target.value))}>{a.choices.map((_,i)=><option key={i} value={i}>ทางเลือกที่ {i+1}</option>)}</select></label></fieldset>;
}
function DataChart({records}){const counts=new Map();records.filter(s=>s.trim()).forEach(r=>{const s=r.trim();counts.set(s,(counts.get(s)||0)+1);});const max=Math.max(1,...counts.values());return <div className="authored-chart"><h3>แผนภูมิจากข้อมูลของเรา</h3><small>จำนวนคำตอบ · ใช้ตรวจความตรงกันกับข้อมูลดิบ</small>{[...counts].slice(0,8).map(([label,n])=><div key={label}><span>{label}</span><i style={{width:`${n/max*100}%`}}/><strong>{n}</strong></div>)}{!counts.size&&<p>ใส่ข้อมูลเพื่อสร้างแผนภูมิ</p>}</div>;}
function ReadContent({content,fields,kind,scope}){const a=content.artifact;return <div className="submitted-content">{fields.map(([k,label])=><div key={k}><strong>{label}</strong><p>{content[k]||'—'}</p></div>)}{kind==='project'&&a&&<div><h3>ชิ้นงานที่ส่ง</h3>{scope<=2?<><div className="authoring-grid robot-grid">{Array.from({length:25},(_,i)=>{const x=i%5,y=Math.floor(i/5),same=p=>p[0]===x&&p[1]===y;return <div className={`robot-cell ${a.walls.some(same)?'wall':''}`} key={i}>{same(a.start)?'🤖':same(a.goal)?'🚩':a.walls.some(same)?'🪨':<small>{x+1},{y+1}</small>}</div>;})}</div><p>{a.commands.map(t=>commandLabels[t]).join(' → ')}</p></>:scope===3?<><p>คำถาม: {a.question}</p><p>แหล่งข้อมูล: {a.source}</p><p>ข้อมูลดิบ: {a.records.join(', ')}</p><DataChart records={a.records}/></>:<><p>{a.story}</p>{a.choices.map((c,i)=><div className="story-choice" key={i}><strong>{i+1}. {c}{i===a.safe?' (ทางเลือกที่ผู้เรียนเสนอ)':''}</strong><p>{a.outcomes[i]}</p></div>)}</>}</div>}</div>;}

function TeacherPortfolio({data,levels,reload,onDirty}){
 const [selected,setSelected]=useState(null),[filter,setFilter]=useState('all'),[room,setRoom]=useState(''),[dirty,setDirty]=useState(false);const changed=v=>{setDirty(v);onDirty(v);};const entry=data.entries.find(e=>e.id===selected);
 useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const title=e=>e.kind==='project'?data.projects.find(p=>p.id===e.scope_id)?.title:`บันทึกด่าน ${levels.find(l=>l.id===e.scope_id)?.number}`;
 const entries=data.entries.filter(e=>(filter==='all'||(filter==='pending'?e.state==='submitted':e.kind===filter))&&(!room||e.student.classroom===room));
 return <section className="portfolio"><div className="page-heading"><div><span className="eyebrow">STUDENT THINKING & CREATIONS</span><h1>ผลงานและสมุดสะท้อนคิด</h1><p>อ่านเหตุผล ดูหลักฐาน และชวนให้ลองคิดต่อ · ครูเห็นเฉพาะฉบับที่นักเรียนส่ง</p></div><button className="secondary" onClick={async()=>{if(!dirty||await confirmDialog('โหลดใหม่จะทิ้งข้อเสนอแนะที่ยังไม่บันทึก ต้องการดำเนินการหรือไม่?')){changed(false);setSelected(null);reload();}}}><RotateCcw size={16}/> โหลดล่าสุด</button></div>{entry?<><button className="text-button work-back" onClick={async()=>{if(!dirty||await confirmDialog('กลับรายการงานหรือไม่? ข้อเสนอแนะที่ยังไม่บันทึกจะไม่ถูกเก็บ')){changed(false);setSelected(null);}}}><ArrowLeft size={17}/> กลับรายการงาน</button><ReviewEditor key={`${entry.id}-${entry.version}`} entry={entry} title={title(entry)} project={data.projects.find(p=>p.id===entry.scope_id)} fields={entry.kind==='project'?data.project_fields:data.journal_fields} reload={reload} onDirty={changed}/></>:<><div className="portfolio-filters"><label>แสดงงาน<select aria-label="แสดงงาน" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทั้งหมด</option><option value="pending">รอข้อเสนอแนะ</option><option value="project">ผลงานปลายโลก</option><option value="journal">สมุดสะท้อนคิด</option></select></label><label>ห้องเรียน<select aria-label="ห้องเรียน" value={room} onChange={e=>setRoom(e.target.value)}><option value="">ทุกห้อง</option>{[...new Set(data.entries.map(e=>e.student.classroom))].map(r=><option key={r}>{r}</option>)}</select></label></div><div className="portfolio-list">{entries.map(e=><button className="portfolio-card" key={e.id} onClick={()=>setSelected(e.id)}><span className="portfolio-card-icon">{e.kind==='project'?'🧩':'📓'}</span><span><small>{e.student.name} · {e.student.classroom}</small><strong>{title(e)}</strong><span className={`work-state ${e.state}`}>{e.state==='draft'?'นักเรียนกำลังแก้ไข · ดูได้เฉพาะฉบับที่ส่งเดิม':states[e.state]}</span><small className="work-availability">ฉบับที่ {e.submissions[0].revision} · {date(e.submissions[0].submitted_at)}</small></span><ArrowRight size={18}/></button>)}</div>{!entries.length&&<p className="empty">ยังไม่มีงานที่ส่งตรงกับตัวกรองนี้ ร่างส่วนตัวของนักเรียนจะไม่แสดงที่นี่</p>}</>}</section>;
}
function ReviewEditor({entry,title,project,fields,reload,onDirty}){
 const [feedback,setFeedback]=useState(''),[outcome,setOutcome]=useState('reviewed'),[rubric,setRubric]=useState({reasoning:'',evidence:'',transfer:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const latest=entry.submissions[0];
 useEffect(()=>()=>onDirty(false),[]);

 async function send(e){e.preventDefault();setBusy(true);setError('');try{await api(`/teacher/portfolio/${entry.id}/review`,{method:'POST',body:{version:entry.version,submission_id:latest.id,feedback,outcome,rubric}});onDirty(false);await reload();notifyDialog('ส่งข้อเสนอแนะเรียบร้อยแล้ว');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="work-layout"><div className="work-editor"><span className="eyebrow">{entry.student.name} · {entry.student.classroom} · ฉบับที่ {latest.revision}</span><h2>{title}</h2><ReadContent content={latest.content} fields={fields} kind={entry.kind} scope={entry.scope_id}/><History items={entry.submissions} fields={fields} kind={entry.kind} scope={entry.scope_id}/></div><aside className="work-guide"><h3>ข้อเสนอแนะเพื่อพัฒนา</h3>{project&&entry.kind==='project'&&<ul>{project.criteria.map(c=><li key={c}>{c}</li>)}</ul>}{entry.state==='submitted'?<form onSubmit={send}><label>ข้อเสนอแนะจากครู<textarea rows={6} maxLength={1800} required value={feedback} onChange={e=>{setFeedback(e.target.value);onDirty(true);}} placeholder="บอกจุดที่ทำได้ดี หลักฐานที่ยังขาด และคำถามชวนคิดต่อ"/></label>{entry.kind==='project'&&Object.entries(rubricNames).map(([k,label])=><label key={k}>{label}<select aria-label={label} required value={rubric[k]} onChange={e=>{setRubric({...rubric,[k]:e.target.value});onDirty(true);}}><option value="">เลือกระดับ</option>{Object.entries(rubricLevels).map(([v,text])=><option value={v} key={v}>{text}</option>)}</select></label>)}<label>ผลการอ่านงาน<select aria-label="ผลการอ่านงาน" value={outcome} onChange={e=>{setOutcome(e.target.value);onDirty(true);}}><option value="reviewed">ให้ข้อเสนอแนะแล้ว</option><option value="revision_requested">ชวนปรับปรุงและส่งอีกครั้ง</option></select></label><button className="primary full" disabled={busy}>{busy?'กำลังบันทึก…':'ส่งข้อเสนอแนะ'}</button>{error&&<NoticeModal message={error} onClose={()=>setError('')}/>}</form>:<p className="notice">{entry.state==='draft'?'นักเรียนเปิดฉบับแก้ไขอยู่ กรุณารอส่งฉบับใหม่ก่อนให้ข้อเสนอแนะ':'ตรวจฉบับนี้แล้ว สามารถดูประวัติข้อเสนอแนะได้ด้านล่างผลงาน'}</p>}</aside></div>;
}
