import {NoticeModal,confirmDialog,notifyDialog} from './components/Notifications';
import {useEffect,useRef,useState} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import {Map,BookOpen,Trophy,Gift,Settings,RotateCcw,LogOut,ChevronRight,ArrowRight,ArrowLeft,Lock,Check,Star,Flame,Leaf,Code2,Database,Shield,Users,Download,Plus,Search,X,GraduationCap,Gamepad2,Target,Clock,Menu,Eye,KeyRound,Pencil,CheckCircle2} from 'lucide-react';
import Portfolio from './components/Portfolio';
import PixelWorld from './components/PixelWorld';
import SpotlightCard from './components/SpotlightCard';
import MissionGame from './components/MissionGame';
import {WORLD_PLAY} from './components/WorldAdventure';
function Game(props){return <MissionGame {...props}/>;}
import {api,number,downloadScores} from './lib';
const unitIcons=[Leaf,Code2,Database,Shield];

function Modal({children,onClose,label='รายละเอียด'}){const ref=useRef();useEffect(()=>{const el=ref.current;el.showModal();return()=>el.close();},[]);return <dialog ref={ref} className="modal" aria-label={label} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><button className="modal-close icon-btn" aria-label="ปิด" onClick={onClose}><X size={20}/></button>{children}</dialog>;}
function Brand(){return <div className="brand"><span className="brand-icon"><Code2 size={26}/></span><div>Flow<span>Quest</span><small>ผจญภัย ป.5</small></div></div>;}

export default function App({onExit}){
 const [user,setUser]=useState(null),[boot,setBoot]=useState(true),[fatal,setFatal]=useState(''),[data,setData]=useState(null),[profile,setProfile]=useState(null),[board,setBoard]=useState([]),[view,setView]=useState('map'),[unit,setUnit]=useState(1),[lesson,setLesson]=useState(null),[game,setGame]=useState(null),[mobile,setMobile]=useState(false),[toast,setToast]=useState(''),[portfolioScope,setPortfolioScope]=useState(null),[portfolioDirty,setPortfolioDirty]=useState(false),[portfolioVisit,setPortfolioVisit]=useState(0);
 async function refresh(){const [p,b]=await Promise.all([api('/me'),api('/leaderboard')]);setProfile(p);setBoard(b.entries);}
 useEffect(()=>{api('/session').then(d=>setUser(d.user)).catch(e=>setFatal(e.message)).finally(()=>setBoot(false));},[]);
 useEffect(()=>{if(!user)return;let cancelled=false;Promise.all([api('/curriculum'),api('/me'),api('/leaderboard')]).then(([c,p,b])=>{if(cancelled)return;setData(c);setProfile(p);setBoard(b.entries);}).catch(e=>setFatal(e.message));return()=>{cancelled=true;};},[user]);

 async function logout(){if(portfolioDirty&&!await confirmDialog('มีข้อความที่ยังไม่บันทึก ต้องการกลับ FlowQuest หรือไม่?'))return;onExit();}
 const nav=async(v)=>{if(portfolioDirty&&!await confirmDialog('มีข้อความที่ยังไม่บันทึก ต้องการออกจากหน้านี้หรือไม่?'))return;setPortfolioDirty(false);setPortfolioScope(null);setPortfolioVisit(n=>n+1);setView(v);setMobile(false);};
 if(boot)return <div className="loading"><Brand/><p>เตรียมโลกผจญภัย…</p></div>;
 if(fatal)return <ConnectionFailure message={fatal}/>;
 if(!user)return <ConnectionFailure message="กรุณาเข้าสู่ระบบ FlowQuest อีกครั้ง"/>;
 if(!data||!profile)return <div className="loading"><Brand/><p>กำลังโหลดบทเรียนและความก้าวหน้า…</p></div>;
 const completed=profile.completed||0,totalLevels=data.levels.length,percent=Math.round(completed/data.levels.length*100),currentLevel=data.levels.find(l=>!profile.progress.some(p=>p.level_id===l.id&&p.completed))||data.levels[data.levels.length-1];
 const getProgress=id=>profile.progress.find(p=>p.level_id===id);
 const isUnlocked=id=>{const l=data.levels.find(l=>l.id===id);return l&&(!l.prerequisite_id||getProgress(id)?.completed||getProgress(id)?.read||getProgress(l.prerequisite_id)?.completed);};
 async function start(level){try{await api(`/levels/${level.id}/read`,{method:'POST'});const a=await api(`/levels/${level.id}/start`,{method:'POST'});setLesson(null);setGame({level,attempt:a});await refresh();}catch(e){setToast(e.message);}}
 return <div className="app-shell"><aside className={`sidebar ${mobile?'open':''}`}><Brand/><span className="nav-label">พื้นที่การเรียนรู้</span><nav>{(user.role==='teacher'?[[Users,'teacher','ห้องเรียนของฉัน'],[BookOpen,'lessons','คลังบทเรียน'],[Pencil,'portfolio-review','ผลงานและบันทึก']]:[[Map,'map','แผนที่ผจญภัย'],[BookOpen,'lessons','บทเรียนของฉัน'],[Trophy,'leaderboard','อันดับนักผจญภัย'],[Gift,'rewards','คลังรางวัล'],[Pencil,'projects','ภารกิจสร้างผลงาน'],[BookOpen,'journal','สมุดสะท้อนคิด']]).map(([Icon,id,label])=><button key={id} onClick={()=>nav(id)} className={(view===id||(user.role==='teacher'&&view==='map'&&id==='teacher'))?'active':''}><Icon size={20}/>{label}{id==='rewards'&&completed>0&&<span className="nav-count">{completed}</span>}</button>)}</nav><div className="sidebar-note"><span>🌱</span><strong>เก่งขึ้นได้ทุกวัน</strong><p>ไม่ต้องรีบไปให้ไกล<br/>แค่ลองใหม่ ก็ได้เรียนรู้แล้ว</p></div><div className="sidebar-bottom"><span className="avatar">{user.role==='teacher'?'👩‍🏫':'🧑‍🚀'}</span><div><strong>{user.name}</strong><small>{user.role==='teacher'?'ครูผู้สอน':`นักเรียน ${user.classroom}`}</small></div><button className="icon-btn" onClick={logout} title="กลับ FlowQuest" aria-label="กลับ FlowQuest"><LogOut size={17}/></button></div></aside>{mobile&&<button className="sidebar-scrim" aria-label="ปิดเมนู" onClick={()=>setMobile(false)}/>}
 <div className="main-shell"><header className="topbar"><button className="mobile-menu icon-btn" onClick={()=>setMobile(!mobile)} aria-label="เปิดเมนู"><Menu/></button><button className="secondary" onClick={logout}><ArrowLeft size={16}/>กลับ FlowQuest</button><div className="breadcrumb">ห้องเรียนของเรา <ChevronRight size={14}/><strong>วิทยาการคำนวณ ป.5</strong></div><div className="topbar-right"><span className="class-pill"><GraduationCap size={16}/>{user.classroom}</span><span className="top-avatar">{user.name.slice(0,1)}</span></div></header><main>
 {game?<Game key={game.attempt.id} level={game.level} initialAttempt={game.attempt} onExit={async()=>{try{await api(`/attempts/${game.attempt.id}/abandon`,{method:'POST'});setGame(null);await refresh();}catch(e){setToast(e.message);}}} onComplete={setProfile} onReflect={()=>{setPortfolioScope(game.level.id);setGame(null);setView('journal');}}/>:user.role==='teacher'&&(view==='map'||view==='teacher')?<Teacher levels={data.levels} notify={setToast}/>:<AnimatePresence mode="wait"><motion.div key={view} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.22}}>
 {['projects','journal','portfolio-review'].includes(view)&&<Portfolio key={`${view}-${portfolioVisit}`} view={view} levels={data.levels} teacher={user.role==='teacher'} initialScope={portfolioScope} onDirty={setPortfolioDirty}/>}
 {(view==='map'||view==='lessons')&&<><div className="page-heading"><div><span className="eyebrow">LET’S GO, LITTLE EXPLORER</span><h1>{view==='map'?`พร้อมผจญภัยหรือยัง ${user.name}?`:'บทเรียนของฉัน'} <span className="wave">{view==='map'?'✦':'📖'}</span></h1><p>{view==='map'?'อีกก้าวของการเรียนรู้ เริ่มต้นได้ในวันนี้':'อ่าน ทำความเข้าใจ และลองคิดก่อนออกไปพิชิตด่าน'}</p></div><div className="course-mark"><BookOpen size={17}/> 4 หน่วยการเรียนรู้ · 40 ชั่วโมงตามหลักสูตร</div></div>
 {view==='map'&&<div className="stats-grid"><Stat icon={<Star/>} color="gold" value={number(profile.score)} label="คะแนนสะสม" sub="ใช้คะแนนดีที่สุดแต่ละด่าน"/><Stat icon={<span>🍄</span>} color="coral" value={number(profile.mushrooms)} label="เห็ดที่สะสม" sub="รางวัลจากคำตอบที่ถูก"/><Stat icon={<FlagIcon/>} color="green" value={`${completed} / ${totalLevels}`} label="ด่านที่พิชิต" sub="ค่อย ๆ ก้าวไปทีละด่าน"/><Stat icon={<Trophy/>} color="violet" value={board.find(b=>b.id===user.id)?.score?`#${board.find(b=>b.id===user.id)?.rank}`:'—'} label="อันดับในห้อง" sub={profile.score?'นักผจญภัยประจำห้อง':'ผ่านด่านแรกเพื่อเริ่มจัดอันดับ'}/></div>}
 <div className="content-columns"><div className="adventure-main"><div className="section-heading"><h2>{view==='map'?'เลือกโลกผจญภัย':'เส้นทางการเรียนรู้'}</h2><span>4 โลกที่รอให้ค้นพบ</span></div><div className="world-tabs" role="tablist" aria-label="เลือกหน่วยการเรียนรู้">{data.units.map((u,i)=>{const Icon=unitIcons[i];return <button key={u.id} role="tab" aria-selected={unit===u.id} className={unit===u.id?'selected':''} onClick={()=>setUnit(u.id)}><Icon size={19}/><span>โลก {u.id}</span>{!isUnlocked(data.levels.find(l=>l.unit===u.id).id)&&user.role==='student'&&<Lock size={12}/>}</button>;})}</div>
 <div className={`world-card world-${unit}`}><div className="world-copy"><span className="world-kicker">WORLD {String(unit).padStart(2,'0')} <span>•</span> {data.units[unit-1].hours} ชั่วโมงตามหลักสูตร</span><h2>{data.units[unit-1].world}</h2><p>{data.units[unit-1].title}</p><div className="world-play-summary"><strong>{WORLD_PLAY[unit].icon} {WORLD_PLAY[unit].genre}</strong><small>{WORLD_PLAY[unit].description}</small></div><div className="world-tags"><span>{data.levels.filter(l=>l.unit===unit).length} ด่าน</span><span>{data.units[unit-1].standard}</span></div></div><PixelWorld unit={unit}/><div className="world-bottom"><span><span className="legend-dot"/> {data.levels.filter(l=>l.unit===unit&&getProgress(l.id)?.completed).length} / {data.levels.filter(l=>l.unit===unit).length} ด่านสำเร็จ</span><span>สำรวจ เรียนรู้ แล้วเติบโต <Leaf size={14}/></span></div></div>
 <div className="section-heading levels-heading"><h2>ภารกิจในโลกนี้</h2><span>เรียนทีละด่าน ปลดล็อกทีละก้าว</span></div><div className="level-list">{data.levels.filter(l=>l.unit===unit).map(l=>{let p=getProgress(l.id),unlocked=isUnlocked(l.id)||user.role==='teacher';return <SpotlightCard key={l.id} className={`level-card ${!unlocked?'locked':''}`} spotlightColor="rgba(157, 201, 117, .28)"><span className={`level-number ${p?.completed?'complete':''}`}>{p?.completed?<Check size={23}/>:unlocked?<Gamepad2 size={23}/>:<Lock size={21}/>}</span><div className="level-info"><div className="level-caption">ด่าน {l.number} {p?.completed?<span className="complete-label">สำเร็จแล้ว</span>:unlocked&&<span className="ready-label">พร้อมเรียน</span>}</div><h3>{l.title}</h3><p>{l.subtitle}</p><span className={`mode-badge mode-${l.mode}`}>{l.mode_label} · {l.difficulty}</span><div className="level-meta"><Clock size={13}/>{l.minutes} นาที / กิจกรรม <span>•</span> 🍄 3 <span>•</span> {p?.best_score?`${p.best_score} คะแนน`:'สูงสุด 550 คะแนน'}</div></div><button className={unlocked?'level-go':'locked-button'} disabled={!unlocked} onClick={()=>setLesson(l)} aria-label={`${p?.completed?'ทบทวน':'เริ่มเรียน'} ${l.title}`}>{unlocked?<><span>{p?.completed?'เล่นอีกครั้ง':'เริ่มเรียน'}</span><ArrowRight size={18}/></>:<Lock size={17}/>}</button></SpotlightCard>;})}</div>
 {user.role==='student'&&<div className="world-project-cta"><div><span className="eyebrow">CREATE YOUR OWN</span><h3>ภารกิจสร้างผลงานปลายโลก {unit}</h3><p>ออกแบบ ทดลอง และอธิบายด้วยความคิดของเรา</p></div><button className="primary" onClick={()=>{setPortfolioScope(unit);setView('projects');}}>เริ่มสร้างผลงาน <ArrowRight size={17}/></button></div>}
 <p className="source-note">24 ด่านพื้นฐาน + 27 ด่านดัดแปลงจากกิจกรรมในคู่มือครู สสวท. ป.5 พ.ศ. 2566 · เปิดบทเรียนเพื่อดูที่มา</p></div>
 <aside className="learning-rail"><div className="progress-card"><div className="section-heading"><h3>เส้นทางของฉัน</h3><Target size={19}/></div><div className="progress-ring" style={{'--progress':`${percent*3.6}deg`}}><div><strong>{percent}%</strong><span>สำเร็จแล้ว</span></div></div><p>ทุกด่านคืออีกหนึ่งความสำเร็จ</p><div className="mini-progress"><span>ผ่านด่านเกม</span><strong>{completed} / {totalLevels} ด่าน</strong></div><div className="progress-track"><span style={{width:`${percent}%`}}/></div></div><div className="next-card"><span className="eyebrow"><Flame size={15}/> ภารกิจถัดไป</span><h3>{currentLevel.title}</h3><p>{currentLevel.mode_label} แล้วเก็บเห็ดให้ได้<br/>อย่างน้อย 2 ดอกเพื่อผ่านด่าน</p><button onClick={()=>{setUnit(currentLevel.unit);setLesson(currentLevel);}}>ไปทำภารกิจกัน <ArrowRight size={16}/></button></div><div className="rail-reward"><span className="reward-art">🏅</span><div><span>รางวัลที่รออยู่</span><h3>{currentLevel.reward}</h3><p>ผ่านด่าน {currentLevel.number} เพื่อรับรางวัล</p></div></div><div className="how-to"><h3>คู่มือนักผจญภัย</h3><p><span>01</span> อ่านบทเรียนและลองคิด</p><p><span>02</span> ลงมือแก้ภารกิจตามบทเรียน</p><p><span>03</span> เก็บเห็ด ปลดล็อกโลกใหม่!</p></div></aside></div></>}
 {view==='leaderboard'&&<><PageTitle eyebrow="HALL OF EXPLORERS" title="อันดับนักผจญภัย" text={`เพื่อนร่วมผจญภัยห้อง ${user.classroom} · คะแนนดีที่สุดรวมทุกด่าน`}/><div className="leaderboard-card"><div className="leaderboard-banner"><Trophy size={42}/><div><h2>ทุกความพยายามมีความหมาย</h2><p>เล่นซ้ำเพื่อฝึกฝน และทำลายสถิติของตัวเอง</p></div></div>{board.length===0?<p className="empty">ยังไม่มีนักเรียนในห้องนี้</p>:board.map(b=><div className={`leaderboard-row ${b.id===user.id?'you':''}`} key={b.id}><span className="rank">{b.score?b.rank:'—'}</span><span className="avatar">{b.rank===1&&b.score?'👑':'🧑‍🚀'}</span><div><strong>{b.name}{b.id===user.id?' (คุณ)':''}</strong><small>ผ่านแล้ว {b.completed} ด่าน</small></div><strong>{number(b.score)} <small>คะแนน</small></strong></div>)}<p className="source-note">คะแนนเท่ากันและจำนวนด่านเท่ากันจะได้อันดับร่วม · แสดงเฉพาะชื่อเล่น</p></div></>}
 {view==='rewards'&&<><PageTitle eyebrow="YOUR LITTLE ACHIEVEMENTS" title="คลังรางวัลของฉัน" text={`ความพยายามของคุณกลายเป็นรางวัลแล้ว ${completed} ชิ้น`}/><div className="reward-grid">{data.levels.map(l=>{const owned=getProgress(l.id)?.completed;return <SpotlightCard key={l.id} className={`reward-card ${owned?'owned':''}`}><span className="reward-emoji">{owned?(l.stage===6?'👑':l.stage%2===1?'🎖️':'🏅'):'🔒'}</span><span className="eyebrow">WORLD {l.unit} · LEVEL {l.number}</span><h3>{l.reward}</h3><p>{owned?'เก็บเข้าคลังแล้ว เยี่ยมมาก!':`ผ่านด่าน ${l.number} เพื่อปลดล็อก`}</p>{owned&&<span className="complete-label"><Check size={13}/> ได้รับแล้ว</span>}</SpotlightCard>;})}</div></>}
 </motion.div></AnimatePresence>}
 </main><footer className="app-footer"><span>FlowQuest · พื้นที่เล็ก ๆ ของนักคิดที่ยิ่งใหญ่</span><span>วิทยาการคำนวณ ชั้นประถมศึกษาปีที่ 5</span></footer></div>
 {lesson&&<Lesson level={lesson} unit={data.units[lesson.unit-1]} teacher={user.role==='teacher'} onClose={()=>setLesson(null)} onStart={()=>start(lesson)}/>}
 {toast&&<NoticeModal message={toast} variant="info" onClose={()=>setToast('')}/>}
 </div>;
}
function FlagIcon(){return <Target/>;}
function Stat({icon,color,value,label,sub}){return <div className="stat"><div className={`stat-icon ${color}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>;}
function PageTitle({eyebrow,title,text}){return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></div>;}
function Lesson({level,unit,teacher,onClose,onStart}){const [checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[reflection,setReflection]=useState('');return <Modal onClose={onClose} label={level.title}><div className="lesson-modal"><span className="eyebrow">{unit.world} · ด่าน {level.number}</span><h1>{level.title}</h1><p className="lesson-subtitle">{level.subtitle}</p>{level.source&&<div className="guide-source"><strong>กิจกรรม {level.source.activity} · บทที่ {level.source.chapter} {level.source.chapter_title}</strong><p>{level.source.label} · หน้าเล่ม {level.source.printed_pages} · ตารางกิจกรรมใน PDF หน้า {level.source.pdf_page}</p><small>ดัดแปลงแนวทางกิจกรรมเป็นโจทย์ใหม่ในระบบ ไม่ใช่แบบฝึกต้นฉบับหรือเฉลยทางการ</small></div>}<div className="lesson-standard"><BookOpen size={16}/>{level.standard||unit.standard}</div><div className="lesson-game-info"><h3>{WORLD_PLAY[level.unit].icon} {WORLD_PLAY[level.unit].genre}</h3><p>{WORLD_PLAY[level.unit].description}</p><strong>🎮 {level.mode_label} · {level.difficulty}</strong><p>{level.mode==='platformer'?'เล่นภารกิจตามรูปแบบของโลก ทำสำเร็จอย่างน้อย 2 จาก 3 ข้อเพื่อผ่านด่าน':level.instructions}</p><small>เหตุผลที่ใช้เกมนี้: {level.rationale}</small></div><h3>เมื่อจบด่านนี้ ฉันจะ…</h3><ul className="learning-objectives">{level.objectives.map(o=><li key={o}>{o}</li>)}</ul><h3>เรียนรู้ก่อนออกเดินทาง</h3>{level.lesson.map((p,i)=><div className="lesson-paragraph" key={i}><span>{i+1}</span><p>{p}</p></div>)}<div className="example-box"><strong>💡 ลองดูตัวอย่าง</strong><p>{level.example}</p></div><div className="activity-box"><strong>✏️ ตานักผจญภัยลองคิด</strong><p>{level.activity}</p><textarea rows={3} value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="เขียนแนวคิดของตัวเอง หรือทดลองบนกระดาษ" aria-label="แนวคิดสำหรับกิจกรรม"/><small>พื้นที่ฝึกคิดส่วนตัว ไม่บันทึกหรือคิดคะแนน</small></div>{!teacher&&<><label className="check-label"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> ฉันอ่านบทเรียนและลองทำกิจกรรมแล้ว พร้อมออกผจญภัย!</label><div className="notice">ทำสำเร็จอย่างน้อย 2 ใน 3 ภารกิจ เพื่อผ่านด่าน · มีหัวใจ 3 ดวง</div><button className="primary full" disabled={!checked||busy} onClick={async()=>{setBusy(true);try{await onStart();}finally{setBusy(false);}}}>{busy?'กำลังเตรียมด่าน…':'เริ่มผจญภัย'}<Gamepad2 size={19}/></button></>}</div></Modal>;}

function Teacher({levels,notify}){
 const [students,setStudents]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[room,setRoom]=useState(''),[detail,setDetail]=useState(null),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[resetting,setResetting]=useState(null);
 const resetBusy=useRef(false);
 const reload=async()=>{setError('');try{const d=await api('/teacher/students');setStudents(d.students);}catch(e){setError(e.message);}finally{setLoading(false);}};
 useEffect(()=>{reload();},[]);
 const filtered=students.filter(s=>(!room||s.classroom===room)&&`${s.name} ${s.username}`.toLowerCase().includes(query.toLowerCase())),active=students.filter(s=>s.active),average=active.length?Math.round(active.reduce((sum,s)=>sum+s.completed,0)/active.length/levels.length*100):0;
 const pageCount=Math.max(1,Math.ceil(filtered.length/pageSize));
 const currentPage=Math.min(page,pageCount);
 const startIndex=(currentPage-1)*pageSize;
 const pageStudents=filtered.slice(startIndex,startIndex+pageSize);
 useEffect(()=>{setPage(currentPage);},[currentPage]);
 async function resetLevel(level){
  if(resetBusy.current||!detail)return;
  resetBusy.current=true;
  const student=detail.student;
  try{
   const confirmed=await confirmDialog(`รีเซ็ตด่าน ${level.number} “${level.title}” ของ ${student.name}?\n\nผลผ่าน คะแนน เห็ด และ XP ของด่านนี้จะถูกล้าง รอบที่กำลังเล่นจะสิ้นสุด และเริ่มเล่นใหม่ได้ ประวัติเดิมจะระบุว่า “ครูรีเซ็ต”\n\nด่านอื่นและแฟ้มผลงานยังอยู่ ด่านถัดไปที่ยังไม่เริ่มอาจล็อกจนผ่านด่านนี้อีกครั้ง`);
   if(!confirmed)return;
   setResetting(level.id);
   const data=await api(`/teacher/students/${student.id}/levels/${level.id}/reset`,{method:'POST'});
   setDetail(data);setStudents(rows=>rows.map(row=>row.id===student.id?data.student:row));
   notify(data.reset?'รีเซ็ตด่านเรียบร้อยแล้ว นักเรียนสามารถเริ่มเล่นใหม่ได้':'ด่านนี้ถูกรีเซ็ตแล้ว');
  }catch(e){notify(e.message);}finally{setResetting(null);resetBusy.current=false;}
 }
 async function show(s){try{setDetail(await api(`/teacher/students/${s.id}/attempts`));}catch(e){notify(e.message);}}
 return <><div className="page-heading"><div><span className="eyebrow">TEACHER’S ROOM</span><h1>ห้องเรียนของฉัน</h1><p>ดูแลทุกก้าวของนักเรียน ให้ทุกคนเติบโตไปด้วยกัน</p></div><a className="secondary" href="/teacher/courses">จัดการรายวิชาใน FlowQuest</a></div><div className="stats-grid teacher-stats"><Stat icon={<Users/>} color="green" label="นักเรียนที่ใช้งาน" value={active.length} sub={`ทั้งหมด ${students.length} คน`}/><Stat icon={<Target/>} color="violet" label="ความก้าวหน้าเฉลี่ย" value={`${average}%`} sub="จากนักเรียนที่เปิดใช้งาน"/><Stat icon={<Trophy/>} color="gold" label="เรียนครบทุกด่าน" value={active.filter(s=>s.completed===levels.length).length} sub={`นักเรียนที่ผ่าน ${levels.length} ด่าน`}/></div><section className="teacher-panel"><div className="table-toolbar"><h2>รายชื่อนักเรียน</h2><div><label className="search-field"><Search size={17}/><input aria-label="ค้นหานักเรียน" placeholder="ค้นหาชื่อ หรือชื่อผู้ใช้" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><select aria-label="กรองห้องเรียน" value={room} onChange={e=>{setRoom(e.target.value);setPage(1);}}><option value="">ทุกห้องเรียน</option>{[...new Set(students.map(s=>s.classroom))].sort().map(r=><option key={r}>{r}</option>)}</select><button className="secondary" onClick={()=>downloadScores(room).catch(e=>setError(e.message))}><Download size={17}/> ดาวน์โหลดคะแนน XLSX</button></div></div><p className="export-note">ดาวน์โหลด XLSX ของทุกคนในห้องที่เลือก เรียงเลขที่จากน้อยไปมาก พร้อมคะแนนแยกรายด่าน ผู้ที่ไม่มีเลขที่อยู่ท้ายรายการ (ไม่กรองตามคำค้น)</p>{error&&<NoticeModal message={error} onClose={()=>setError('')}><button type="button" className="secondary" onClick={()=>{setError('');reload();}}>ลองใหม่</button></NoticeModal>}{loading?<p className="empty">กำลังโหลดรายชื่อ…</p>:<div className="table-wrap"><table><thead><tr><th>นักเรียน</th><th>ห้องเรียน</th><th>ความก้าวหน้า</th><th>คะแนน</th><th>ตอบถูก</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{pageStudents.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.username}</small></td><td>{s.classroom}</td><td><div className="table-progress"><div className="progress-track"><span style={{width:`${s.completed/levels.length*100}%`}}/></div><small>{s.completed}/{levels.length} ด่าน</small></div></td><td><strong>{number(s.score)}</strong></td><td>{s.accuracy===null?'—':`${s.accuracy}%`}</td><td><span className={s.active?'complete-label':'disabled-label'}>{s.active?'ใช้งาน':'ปิดบัญชี'}</span></td><td><div className="row-actions"><button className="icon-btn" aria-label={`ดูความคืบหน้า ${s.name}`} onClick={()=>show(s)}><Eye size={18}/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<p className="empty">{students.length?'ไม่พบนักเรียนที่ตรงกับการค้นหา':'ยังไม่มีนักเรียน กด “เพิ่มนักเรียน” เพื่อเริ่มต้น'}</p>}</div>}{!loading&&<div className="student-pagination">
 <p role="status" aria-live="polite">{filtered.length?`แสดง ${startIndex+1}–${Math.min(startIndex+pageSize,filtered.length)} จาก ${filtered.length} คน`:'ไม่พบรายชื่อนักเรียน'}</p>
 <label className="student-page-size">แสดงหน้าละ <select aria-label="จำนวนนักเรียนต่อหน้า" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);}}>{[10,20,50].map(size=><option key={size} value={size}>{size} คน</option>)}</select></label>
 <nav aria-label="แบ่งหน้ารายชื่อนักเรียน">
  <button type="button" className="secondary" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ArrowLeft size={16}/>ก่อนหน้า</button>
  <span>หน้า {currentPage} / {pageCount}</span>
  <button type="button" className="secondary" disabled={currentPage===pageCount} onClick={()=>setPage(currentPage+1)}>ถัดไป<ArrowRight size={16}/></button>
 </nav>
 </div>}</section><p className="source-note">ความถูกต้องคำนวณจากทุกข้อที่เคยตอบ รวมรอบที่เริ่มใหม่ · คะแนนสะสมใช้คะแนนดีที่สุดของด่านที่ผ่านเท่านั้น</p>
 {detail&&<Modal onClose={()=>{if(!resetBusy.current)setDetail(null);}} label={`ความคืบหน้า ${detail.student.name}`}><div className="student-detail"><span className="eyebrow">STUDENT PROGRESS</span><h1>{detail.student.name}</h1><p>{detail.student.classroom} · {detail.student.score} คะแนน · เล่น {detail.student.attempts} ครั้ง</p><h3>ผลการเรียนแต่ละด่าน</h3><p className="reset-help">รีเซ็ตเฉพาะด่านที่เลือก เพื่อล้างผลเล่นและ XP ของด่านนั้น ประวัติเดิมเก็บไว้ให้ตรวจสอบ</p>{levels.map(l=>{const p=detail.student.progress.find(p=>p.level_id===l.id);const canReset=p?.completed||p?.best_score||detail.attempts.some(a=>a.level_id===l.id&&a.status!=='reset');return <div className="detail-level" key={l.id}><span>{l.number}</span><div><strong>{l.title}</strong><small>{l.mode_label} · {p?.completed?'ผ่านแล้ว':p?.read?'อ่านแล้ว ยังไม่ผ่าน':'ยังไม่เริ่ม'}</small></div><div className="detail-level-actions"><strong>{p?.best_score||0} <small>คะแนน</small></strong><button type="button" className="secondary reset-level-button" aria-label={`รีเซ็ตด่าน ${l.number} ${l.title}`} disabled={!canReset||resetting!==null} onClick={()=>resetLevel(l)}><RotateCcw size={15}/>{resetting===l.id?'กำลังรีเซ็ต…':'รีเซ็ตด่าน'}</button></div></div>;})}<h3>ประวัติการเล่น</h3>{detail.attempts.length?detail.attempts.map(a=><div className="attempt-row" key={a.id}><span>ด่าน {levels.find(l=>l.id===a.level_id)?.number||a.level_id}<small>{new Date(a.started_at).toLocaleString('th-TH')}</small></span><span>ถูก {a.correct}/{a.answered} · เสียหัวใจ {a.hits}</span><span>{{active:'กำลังเล่น',failed:'ไม่ผ่าน',completed:'ผ่านแล้ว',abandoned:'เริ่มใหม่ / ออกจากเกม',reset:'ครูรีเซ็ต'}[a.status]}</span></div>):<p className="empty">ยังไม่มีประวัติการเล่น</p>}</div></Modal>}
 </>;
}

function ConnectionFailure({message}){const [open,setOpen]=useState(true);return <div className="loading"><Brand/><h2>เชื่อมต่อระบบไม่ได้</h2><button className="primary" onClick={()=>location.reload()}>ลองใหม่</button>{open&&<NoticeModal message={message} onClose={()=>setOpen(false)}/>}</div>;}
