"""add gender to character config

Revision ID: 0cad5d97af58
Revises: 2080f638062b
Create Date: 2026-07-02 08:31:32.120191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cad5d97af58'
down_revision = '2080f638062b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_config', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
