"""add brainstorm questions

Revision ID: 1b5448b9061e
Revises: 9113988b9a7c
Create Date: 2026-06-30 21:19:33.275160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5448b9061e'
down_revision = '9113988b9a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brainstorm_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['brainstorm_boards.board_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    with op.batch_alter_table('brainstorm_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'brainstorm_questions', ['question_id'], ['question_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brainstorm_cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('question_id')

    op.drop_table('brainstorm_questions')
    # ### end Alembic commands ###
