"""add character system and shop

Revision ID: 2080f638062b
Revises: af6e8419f851
Create Date: 2026-07-01 22:57:36.898037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2080f638062b'
down_revision = 'af6e8419f851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('price_points', sa.Integer(), nullable=True),
    sa.Column('level_required', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_limited', sa.Boolean(), nullable=True),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('render_config', sa.JSON(), nullable=True),
    sa.Column('preview_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('character_config',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skin_color', sa.String(length=20), nullable=True),
    sa.Column('head_shape', sa.String(length=20), nullable=True),
    sa.Column('eye_type', sa.String(length=20), nullable=True),
    sa.Column('eye_color', sa.String(length=20), nullable=True),
    sa.Column('mouth_type', sa.String(length=20), nullable=True),
    sa.Column('eyebrow_type', sa.String(length=20), nullable=True),
    sa.Column('hair_color', sa.String(length=20), nullable=True),
    sa.Column('body_config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_table('trade_listings',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('price_points', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['user_inventory.inventory_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_table('trade_offers',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('offer_inventory_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_inventory_id'], ['user_inventory.inventory_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['trade_listings.trade_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_offers')
    op.drop_table('trade_listings')
    op.drop_table('user_inventory')
    op.drop_table('character_config')
    op.drop_table('shop_items')
    # ### end Alembic commands ###
