"""add sudoku module (puzzles, events, usermission counters)

Revision ID: 268035f85fcb
Revises: 804c2854d00d
Create Date: 2026-07-05 13:55:33.268193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268035f85fcb'
down_revision = '804c2854d00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sudoku_puzzles',
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('box_rows', sa.Integer(), nullable=True),
    sa.Column('box_cols', sa.Integer(), nullable=True),
    sa.Column('symbol_set', sa.JSON(), nullable=False),
    sa.Column('render_mode', sa.String(length=20), nullable=True),
    sa.Column('given_grid', sa.JSON(), nullable=False),
    sa.Column('solution_grid', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.mission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('puzzle_id')
    )
    op.create_table('sudoku_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_mission_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.Column('value_index', sa.Integer(), nullable=True),
    sa.Column('is_conflict', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['sudoku_puzzles.puzzle_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_mission_id'], ['user_missions.user_mission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hint_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.drop_column('hint_count')
        batch_op.drop_column('attempt_count')

    op.drop_table('sudoku_events')
    op.drop_table('sudoku_puzzles')
    # ### end Alembic commands ###
