"""Add time tracking to UserMission

Revision ID: 4215b92ded23
Revises: 2422c965239b
Create Date: 2026-07-04 14:53:16.630473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4215b92ded23'
down_revision = '2422c965239b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_spent_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.drop_column('time_spent_seconds')
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
