"""Add enable_guidance to SudokuPuzzle

Revision ID: 5d9b3e52d2f2
Revises: 268035f85fcb
Create Date: 2026-07-05 14:55:32.225689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9b3e52d2f2'
down_revision = '268035f85fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sudoku_puzzles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_guidance', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sudoku_puzzles', schema=None) as batch_op:
        batch_op.drop_column('enable_guidance')

    # ### end Alembic commands ###
