"""add max_attempts to sudoku

Revision ID: 69801ac71417
Revises: 5d9b3e52d2f2
Create Date: 2026-07-05 15:42:49.992791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69801ac71417'
down_revision = '5d9b3e52d2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sudoku_puzzles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sudoku_puzzles', schema=None) as batch_op:
        batch_op.drop_column('max_attempts')

    # ### end Alembic commands ###
