"""Add min_score to Mission

Revision ID: 88a36f0db3ae
Revises: 6496ae42db65
Create Date: 2026-08-05 11:54:37.287826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a36f0db3ae'
down_revision = '6496ae42db65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('min_score')

    # ### end Alembic commands ###
