"""Add current_nodes and current_edges to UserMission

Revision ID: 9072b22100c8
Revises: db5e80ff78f5
Create Date: 2026-06-30 14:32:33.172320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9072b22100c8'
down_revision = 'db5e80ff78f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_nodes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('current_edges', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.drop_column('current_edges')
        batch_op.drop_column('current_nodes')

    # ### end Alembic commands ###
