"""avatar editor v2 upgrade

Revision ID: ab4341e28c0d
Revises: 0cad5d97af58
Create Date: 2026-07-02 08:51:03.577569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4341e28c0d'
down_revision = '0cad5d97af58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_outfits',
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('outfit_data', sa.JSON(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('thumbnail_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outfit_id')
    )
    with op.batch_alter_table('character_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('head_scale', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proportion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nose_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('beard_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('makeup_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('expression', sa.String(length=20), nullable=True))

    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_bundle', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bundle_items', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.drop_column('bundle_items')
        batch_op.drop_column('is_bundle')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('tags')
        batch_op.drop_column('thumbnail_color')

    with op.batch_alter_table('character_config', schema=None) as batch_op:
        batch_op.drop_column('expression')
        batch_op.drop_column('makeup_type')
        batch_op.drop_column('beard_type')
        batch_op.drop_column('nose_type')
        batch_op.drop_column('proportion')
        batch_op.drop_column('body_type')
        batch_op.drop_column('head_scale')
        batch_op.drop_column('body_width')
        batch_op.drop_column('body_height')

    op.drop_table('avatar_outfits')
    # ### end Alembic commands ###
