"""add show_student_posts to brainstorm board

Revision ID: ae5d53d1f95f
Revises: 1b5448b9061e
Create Date: 2026-07-01 06:50:45.367721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5d53d1f95f'
down_revision = '1b5448b9061e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brainstorm_boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_student_posts', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brainstorm_boards', schema=None) as batch_op:
        batch_op.drop_column('show_student_posts')

    # ### end Alembic commands ###
