"""add quiz types

Revision ID: af6e8419f851
Revises: ea7a6be708f2
Create Date: 2026-07-01 22:26:48.185443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6e8419f851'
down_revision = 'ea7a6be708f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcq_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('question_metadata', sa.JSON(), nullable=True))

    with op.batch_alter_table('mcq_user_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcq_user_answers', schema=None) as batch_op:
        batch_op.drop_column('answer_data')

    with op.batch_alter_table('mcq_questions', schema=None) as batch_op:
        batch_op.drop_column('question_metadata')
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###
