"""Add solution_nodes and edges

Revision ID: db5e80ff78f5
Revises: 68d50e8024dc
Create Date: 2026-06-30 13:59:39.111411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5e80ff78f5'
down_revision = '68d50e8024dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution_nodes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('solution_edges', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('solution_edges')
        batch_op.drop_column('solution_nodes')

    # ### end Alembic commands ###
