"""Add MCQ models

Revision ID: ea7a6be708f2
Revises: ae5d53d1f95f
Create Date: 2026-07-01 17:15:01.430689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7a6be708f2'
down_revision = 'ae5d53d1f95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcq_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('xp_points', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.mission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('mcq_choices',
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('choice_text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['mcq_questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('choice_id')
    )
    op.create_table('mcq_user_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('user_mission_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_choice_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['mcq_questions.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_choice_id'], ['mcq_choices.choice_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_mission_id'], ['user_missions.user_mission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id')
    )
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('randomize_questions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('randomize_choices', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('randomize_choices')
        batch_op.drop_column('randomize_questions')
        batch_op.drop_column('time_limit_seconds')

    op.drop_table('mcq_user_answers')
    op.drop_table('mcq_choices')
    op.drop_table('mcq_questions')
    # ### end Alembic commands ###
