"""Add updated_at to UserMission

Revision ID: f1bc60036444
Revises: 9072b22100c8
Create Date: 2026-06-30 15:16:03.748591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bc60036444'
down_revision = '9072b22100c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
