"""add min_xp_to_pass to sudoku

Revision ID: f561f91b3abd
Revises: 69801ac71417
Create Date: 2026-07-05 16:02:06.060476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f561f91b3abd'
down_revision = '69801ac71417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sudoku_puzzles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_xp_to_pass', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sudoku_puzzles', schema=None) as batch_op:
        batch_op.drop_column('min_xp_to_pass')

    # ### end Alembic commands ###
